### ISSUE TITLE
calculate focal length

### ISSUE THREAD

**Issue by shilezhang** [rayryeng/XiaohuLuVPDetection#4]
`The image has been reduced down to 1/4 of the resolution for ease. The new image has dimensions of 968 x 648. The image was originally taken with a Nikon D40X whose focal length is 18 mm and the CCD width is 15.8 mm. Therefore, the estimated focal length should be:
968 x (18 / 15.8) = 1102.79 pixels`

Hi
If I use cv2.calibrateCamera() function [(link)](http://www.dmi.unict.it/~furnari/teaching/CV1617/lab1/) [(link)](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#double%20calibrateCamera(InputArrayOfArrays%20objectPoints,%20InputArrayOfArrays%20imagePoints,%20Size%20imageSize,%20InputOutputArray%20cameraMatrix,%20InputOutputArray%20distCoeffs,%20OutputArrayOfArrays%20rvecs,%20OutputArrayOfArrays%20tvecs,%20int%20flags,%20TermCriteria%20criteria)) to get the intrinsic matrix as:
K = array([[1.73168104e+03, 0.00000000e+00, 2.00203504e+03],
       [0.00000000e+00, 1.73355936e+03, 1.46564886e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
Is 1731.68 and 1733.56 my focal length? 
Thank you in advance!

**Comment by rayryeng** [comment]
It is possible that you have different focal lengths for both the x and y direction. This framework assumes that they're both equal. I currently don't handle the projection from 3D to 2D with different focal lengths for each dimension.

**Comment by shilezhang** [comment]
Hi, thanks for your answer!
By the way, how can I calculate the intrinsic and extrinsic matrix out of the generated 6 vectors?
![image](https://user-images.githubusercontent.com/54859051/79910455-c3e05180-83ec-11ea-9014-60c7909874bd.png)

**Comment by ray-phan-oxb** [comment]
@shilezhang The vanishing points directly tell you what the extrinsics are.  Each vanishing point is a directional vector for each axis.  This method does not find intrinsics - you already know what they are before hand (focal length).

**Comment by rayryeng** [comment]
@shilezhang The vanishing points directly tell you what the rotation matrix is. Each vanishing point is a directional vector for each axis of the camera coordinate system. Please see: https://annals-csis.org/proceedings/2012/pliks/110.pdf - Section III-B. You cannot extract the translation from this method as it only estimates vanishing points.

Also, Xiao Hu Liu's method does not find intrinsics - you already know what they are before hand (focal length) and need to be known prior to using this method.
