### ISSUE TITLE
Replace use of OpenCV's LSD detector 

### ISSUE THREAD

**Issue by rayryeng** [rayryeng/XiaohuLuVPDetection#5]
Currently the algorithm uses OpenCV's LSD detector which has been made unavailable after version 4.0.0.21 due to licensing issues.

This is here to remind me to implement the LSD detector from scratch or to use another module that doesn't have licensing issues so that people aren't forced to use this version of OpenCV.

**Comment by teekie** [comment]
Hello, any progress on LSD fixing?

**Comment by rayryeng** [comment]
@teekie  I haven't had the time to work on this as of late.  There is a third-party module you can install through https://github.com/primetang/pylsd/, but IIRC correctly, this links to the original C++ source, builds a dynamically linked library that interfaces with Python wrappers.  I wanted to write my own NumPy implementation of the detector to escape licensing issues as the original C++ source is GPL.  When I have some spare cycles in the coming months, this will be my top priority.  Thanks for you interest in the work!

**Comment by teekie** [comment]
Thanks Ray! No worries. Totally understand. I am wondering if it will cause big differences if I replace LSD with FastLineDetector. Do you have any insight into it?

**Comment by rayryeng** [comment]
As long as you can robustly detect the lines, there should be no difference. The method uses a modified version of RANSAC to determine the best set of lines in each direction axis direction to find the vanishing point, so even if the lines are noisy, as long as most of them are in line with the vanishing point in each axis, this method should still work. I'd love for you to try to swap this out and see if this works! If it does, I can close this and just swap it out with that detector and not have to implement LSD on my own.

**Comment by teekie** [comment]
Thanks @rayryeng, I have tried out FastLineSegment detector and pylsd-nova. There is actually an enhanced version of pylsd. Let me give you some context first. Basically, I am trying to use Manhattan Line algorithm to reduce some false positives. Let's use original LSD as a baseline, I am able to reduce 74% of the false positives. 
1. Swapping to FastLineSegments, it can only reduce 56% of the false positives. Which means 76% of the original performance
2. Swapping to pylsd-nova, it can reduce 70% of the false positives. Which means 95% of the original performance and I am satisfied with this improvement already. So I am going this path. 

Hopefully my data can help you better decision on how to move forward.

https://github.com/AndranikSargsyan/pylsd-nova

**Comment by rayryeng** [comment]
@teekie thanks for this detailed analysis! As pylsd-nova still links to the original pylsd, I would not be able to license this repo with the MIT license as the C++ code that is built for the LSD algorithm still is under GPL. I'll stick with my original intent to implement the algorithm on my own.

In the meanwhile, please go ahead and use that repo you found. Good luck!

**Comment by rayryeng** [comment]
Closing this as the LSD detector has returned in recent versions of OpenCV 4.x.
