### ISSUE TITLE
Problem with opencv installation

### ISSUE THREAD

**Issue by rajesh-bhat** [rayryeng/XiaohuLuVPDetection#7]
error: Could not find suitable distribution for Requirement.parse('opencv-contrib-python==4.0.0.21')

Tried with pip as well as cloning the code from your repo. Both are throwing the same error.

**Comment by rayryeng** [comment]
I can't reproduce this error. The 4.0.0.21 version is still on pip.

https://pypi.org/project/opencv-contrib-python/4.0.0.21/

**Comment by appledora** [comment]
Hi @rayryeng , I have upgraded pip3 to `(21.1.3)`. Still throws the error :
```
ERROR: No matching distribution found for opencv-contrib-python==4.0.0.21
```

**Comment by rayryeng** [comment]
Related: https://github.com/rayryeng/XiaohuLuVPDetection/issues/8
